apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-api
  template:
    metadata:
      labels:
        app: helloworld-api
    spec:
      containers:
      - name: helloworld-api
        image: deepukurup1980/helloworld-api:latest
        ports:
        - containerPort: 5000
