apiVersion: v1
kind: Service
metadata:
  name: helloworld-api
spec:
  selector:
    app: helloworld-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort # Use LoadBalancer if on cloud, or NodePort if on-premise
