clusterName: "elasticsearch"
nodeGroup: "master"
masterService: ""


replicas: 2
minimumMasterNodes: 1
    
ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - elasticsearch
  tls: []
          
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi