apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
      version: blue
  template:
    metadata:
      labels:
        app: hello-world
        version: blue
    spec:
      containers:
      - name: hello-world
        image: deepukurup1980/helloworld:latest
        ports:
        - containerPort: 5000